name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npx tsc --noEmit
      - run: npm test --silent
      - name: Check for legacy button/input classes in settings
        run: |
          rg -n "btn-primary|btn-secondary|btn-ghost|input-field" "app/(authed)/settings" && echo "Legacy inputs/buttons in settings. Use shadcn/ui components." && exit 1 || exit 0
      - name: Check for legacy card class in admin
        run: |
          rg -n -P "className=\"[^\"]*\scard\s|className=\"card\s|className=\"[^\"]*\scard\"" app/admin \
            && echo "Legacy .card containers in admin. Use <Card>." && exit 1 || exit 0
      - name: Check for legacy buttons in admin
        run: |
          rg -n "btn-primary|btn-secondary|btn-ghost" app/admin && echo "Legacy button classes in admin. Use <Button>." && exit 1 || exit 0
      - name: Repo-wide legacy buttons/inputs (app + components)
        run: |
          rg -n "btn-primary|btn-secondary|btn-ghost|input-field" app components && echo "Legacy classes found. Please migrate to shadcn/ui." && exit 1 || exit 0
      - name: Block legacy card class usage repo-wide
        run: |
          rg -n -P "className=\"[^\"]*\scard\s|className=\"card\s|className=\"[^\"]*\scard\"" app \
            && echo "Legacy .card class found. Use <Card> or token-aligned styles." && exit 1 || exit 0
